# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ ready_for_review ]
  issue_comment:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the LATEST commit on the branch
        if: ${{ github.event.issue.pull_request }}
        uses: actions/checkout@v4
        # with:
          # Use the full Git reference to ensure you check out the current head
          # ${{ github.ref }} will be something like 'refs/heads/feature-branch-1'
          # ref: ${{ github.ref }}

      - name: Confirm the Commit SHA
        run: |
          echo "The checked out SHA is: $(git rev-parse HEAD)"
          echo "PR number: ${{ github.event.issue.number }}"
          cat README.md
