name: CI

on:
  pull_request_target:
    types: [labeled]
    branches:
      - main
  
  push:
    branches:
      - main

jobs:
  ci_and_cleanup:
    if: github.event_name == 'push' || 
      (github.event_name == 'pull_request_target' && github.event.label.name == 'needs-build') 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Needed to remove the label
    steps:

      - name: Checkout PR Code
        uses: actions/checkout@v5

      - name: Comment on the PR
        if: github.event_name == 'pull_request_target'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Use the head commit SHA from the pull_request event context
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          
          # Construct the full commit URL
          COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/$COMMIT_SHA"
          
          # Shorten the SHA for display
          SHORT_SHA="${COMMIT_SHA:0:7}"
          
          # Use gh CLI to create a comment on the PR
          gh pr comment $PR_NUMBER --body "Manual CI build triggered by the 'needs-build' label by **@$TRIGGERING_USER**. 🛠️\n\n- **Commit:** [**$SHORT_SHA**]($COMMIT_URL)\n- **Run Details:** [View the workflow run here]($RUN_URL)"

      - name: Work
        run: |
          echo "PR # ${{ github.event.pull_request.number }}"
          echo "SHA: $(git rev-parse HEAD)"
          cat README.md

      - name: Remove 'needs-build' label
        if: github.event_name == 'pull_request_target'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr edit $PR_NUMBER --remove-label "needs-build"
