on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the LATEST commit on the branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Confirm the Commit SHA
        run: |
          echo "The checked out SHA is: $(git rev-parse HEAD)"
